version: "3.8"

services:
  # Eureka Server
  eureka:
    build:
      context: C:/Users/Vusal/Desktop/MS-Student-Enrollment/eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  # API Gateway
  gateway:
    build:
      context: C:/Users/Vusal/Desktop/MS-Student-Enrollment/gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - eureka
      - student-service
      - university-service
    networks:
      - microservices-network

  # Student MySQL
  student-mysql:
    image: mysql:8.0
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: CodeMatDev019*
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    networks:
      - microservices-network
    volumes:
      - student-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pCodeMatDev019*"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Student Service
  student-service:
    build:
      context: C:/Users/Vusal/Desktop/MS-Student-Enrollment/student-service
      dockerfile: Dockerfile
    container_name: student-service
    depends_on:
      student-mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - microservices-network

  # University MySQL
  university-mysql:
    image: mysql:8.0
    container_name: university-mysql
    environment:
      MYSQL_ROOT_PASSWORD: CodeMatDev019*
      MYSQL_DATABASE: universitydb
    ports:
      - "3308:3306"
    networks:
      - microservices-network
    volumes:
      - university-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pCodeMatDev019*"]
      interval: 5s
      timeout: 3s
      retries: 10

  # University Service
  university-service:
    build:
      context: C:/Users/Vusal/Desktop/MS-Student-Enrollment/university-service
      dockerfile: Dockerfile
    container_name: university-service
    depends_on:
      university-mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  student-mysql-data:
  university-mysql-data: